// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisCit_System.Data;

#nullable disable

namespace SisCit_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816102059_CrearTablaServicios")]
    partial class CrearTablaServicios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SisCit_System.Models.Servicio", b =>
                {
                    b.Property<int>("id_servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_servicio"));

                    b.Property<string>("descripcion_servicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("duracion_servicio")
                        .HasColumnType("int");

                    b.Property<string>("nombre_servicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_servicio");

                    b.ToTable("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
