// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisCit_System.Data;

#nullable disable

namespace SisCit_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817030114_ArregloLlavesForaneasCitasYApellidosUsuario")]
    partial class ArregloLlavesForaneasCitasYApellidosUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SisCit_System.Models.Cita", b =>
                {
                    b.Property<int>("id_cita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cita"));

                    b.Property<DateTime>("fecha_cita")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("hora_cita")
                        .HasColumnType("time");

                    b.Property<int>("id_negocio")
                        .HasColumnType("int");

                    b.Property<int>("id_servicio")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.HasKey("id_cita");

                    b.HasIndex("id_negocio");

                    b.HasIndex("id_servicio");

                    b.HasIndex("id_usuario");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("SisCit_System.Models.Negocio", b =>
                {
                    b.Property<int>("id_negocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_negocio"));

                    b.Property<string>("correo_negocio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion_negocio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_negocio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono_negocio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_negocio");

                    b.ToTable("Negocios");
                });

            modelBuilder.Entity("SisCit_System.Models.Servicio", b =>
                {
                    b.Property<int>("id_servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_servicio"));

                    b.Property<string>("descripcion_servicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("duracion_servicio")
                        .HasColumnType("int");

                    b.Property<string>("nombre_servicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_servicio");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("SisCit_System.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("apellidoMat_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidoPat_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contrasena_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rol_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SisCit_System.Models.Cita", b =>
                {
                    b.HasOne("SisCit_System.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("id_negocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisCit_System.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("id_servicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisCit_System.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");

                    b.Navigation("Servicio");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
